name: test-deploy
on: [workflow_dispatch]
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: test-deploy
        run: |
          helm install test-deploy test-nginx nginx-chart/
